### ISSUE TITLE
Switch the models architecture and add manual feature extraction

### ISSUE THREAD

**Issue by VukIG** [VukIG/Melanoma-Detector#14]

**Comment by VukIG** [comment]
Using this research paper https://www.mdpi.com/1099-4300/22/4/484 make a program which will complement the model by manually extracting ABCDE features from the image. Google ABCDE rule for skin cancer detection. This is a model issue. Create a separate file in the model and manipulate the images so that you manually extract features from the paper

**Comment by shariqmalik10** [comment]
I can work on this. (Also can have more assignees)
