### ISSUE TITLE
Error within the Checkbox component

### ISSUE THREAD

**Issue by VukIG** [VukIG/Melanoma-Detector#9]
Could you decide whether to replace the BouncyCheckbox library with a new one? The issue is with the styling of the component. When the user clicks on the gender checkbox the text gets crossed over and the color of the bubble filling is wrong. You should import colors and use colors.primarycolor . Make sure the check box can only check off one of the boxes

**Comment by OmeedEn** [comment]
pushed new checkbox to feat/diagnosis-screen branch
